#!/usr/bin/env python3
"""Write awesome_memory_vla.bib from the manifest (one @article per arXiv paper)."""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
man = json.load(open(os.path.join(HERE, "papers_manifest.json"), encoding="utf-8"))


def bibkey(x):
    first = x["authors"][0].split()[-1] if x["authors"] else "anon"
    first = re.sub(r"[^A-Za-z]", "", first)
    word = re.sub(r"[^A-Za-z]", "", x["title"].split()[0]) or "paper"
    return f"{first.lower()}{x['published'][:4]}{word.lower()}"


def tex(s):
    return s.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")


seen = set()
out = ["% awesome_memory_vla.bib -- generated by scripts/make_bib.py from scripts/papers_manifest.json", ""]
for x in man:
    k = bibkey(x)
    while k in seen:
        k += "x"
    seen.add(k)
    year = x["published"][:4]
    venue = x["venue"] or f"arXiv {year}"
    journal = venue if not venue.lower().startswith("arxiv") else f"arXiv preprint arXiv:{x['arxiv']}"
    out.append(f"@article{{{k},")
    out.append(f"  title   = {{{{{tex(x['title'])}}}}},")
    out.append(f"  author  = {{{' and '.join(x['authors'])}}},")
    out.append(f"  journal = {{{journal}}},")
    out.append(f"  year    = {{{year}}},")
    out.append(f"  eprint  = {{{x['arxiv']}}},")
    out.append(f"  archivePrefix = {{arXiv}},")
    out.append(f"  url     = {{https://arxiv.org/abs/{x['arxiv']}}},")
    out.append(f"  note    = {{{x['key']}}}")
    out.append("}")
    out.append("")
open(os.path.join(ROOT, "awesome_memory_vla.bib"), "w", encoding="utf-8").write("\n".join(out))
print(f"wrote {len(man)} bib entries")
