#!/usr/bin/env python3
"""Summarise SuperTranslate inspect reports for every translated PDF into papers/zh/QA_SUMMARY.md
(one row per paper: pages, size, error-level issues, codes) plus the residual issue list.
Hand-written explanations of fixes and verified false positives live in papers/zh/QA_REPORT.md.
ASCII-only script; the table headers are English so the file is readable in both READMEs."""
import glob
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ZH = os.path.join(ROOT, "papers", "zh")
rows, residual = [], []
for pdf in sorted(glob.glob(os.path.join(ZH, "*_zh.pdf"))):
    key = os.path.basename(pdf)[:-7]
    rep = pdf[:-4] + ".inspect.json"
    pages = subprocess.run(["pdfinfo", pdf], capture_output=True, text=True).stdout
    pages = next((l.split()[-1] for l in pages.splitlines() if l.startswith("Pages:")), "?")
    size = "%.1f MB" % (os.path.getsize(pdf) / 1e6)
    if os.path.exists(rep):
        d = json.load(open(rep, encoding="utf-8"))
        errs = [i for i in d.get("issues", []) if i.get("severity") == "error"]
        codes = sorted({i["code"] for i in errs})
        status = "clean" if not errs else "%d error-level" % len(errs)
        for i in errs:
            residual.append((key, i["page"], i["code"], i["message"]))
    else:
        status, codes = "no inspect report", []
    rows.append("| %s | %s | %s | %s | %s |" % (key, pages, size, status, ", ".join(codes) or "-"))

out = ["# Translation QA summary (auto-generated by scripts/make_zh_qa.py)", "",
       "Engine: SuperTranslate `pdf_zh_translator`, DeepSeek `deepseek-v4-pro`, `--preserve-graphics-text` (+ `--skip-overflow` for the neighbour papers). "
       "Every PDF was checked page by page with the engine's `inspect`. Explanations of the applied patches and of verified false positives are in [QA_REPORT.md](QA_REPORT.md); patches are recorded in `scripts/zh_patches.json`.", "",
       "| Paper | Pages | Size | inspect | issue codes |", "|---|---|---|---|---|"] + rows
out += ["", "## Residual error-level issues (after patches)", ""]
if residual:
    out += ["| Paper | Page | Code | Message |", "|---|---|---|---|"]
    out += ["| %s | %s | %s | %s |" % (k, p, c, m.replace("|", "/")) for k, p, c, m in residual]
else:
    out.append("None.")
open(os.path.join(ZH, "QA_SUMMARY.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote papers/zh/QA_SUMMARY.md: %d papers, %d residual issues" % (len(rows), len(residual)))
